services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.3.1-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - ./log:/var/log/rabbitmq
      - ./data:/var/lib/rabbitmq/mnesia

  producer-service:
    build: ./producer-service
    container_name: producer-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=root

  consumer-service:
    build: ./consumer-service
    container_name: consumer-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=root

  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - producer-service
      - consumer-service